# 기반 이미지 
FROM python:3.9

# 이미지 내 작업 디렉토리 만들기
WORKDIR /app

# dockerfile이 위치한 모든 파일과 디렉토리 복사
COPY . /app
COPY yolov8_epoch20_best.pt /app/

# 의존성 충돌나서 추가해준 항목
RUN apt-get update && apt-get install -y libgl1-mesa-glx libglib2.0-0

# 이미지를 빌드하는 동안에 실행할 명령어
RUN pip install -r requirements.txt

# 컨테이너가 시작될 때 실행될 기본 명령어
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
